version: '3.3'

services:
  php-env:
    build: .
    volumes:
      - ./project:/var/www/html
    ports:
      - 8100:80
    depends_on:
      - mysql_db
  
  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ccmsdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./project:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8101:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql_db
